# Generated by Django 5.0.3 on 2024-03-09 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(choices=[('starters', 'Starters'), ('salads', 'Salads'), ('desserts', 'Desserts'), ('main_course', 'Main Course'), ('cool_drinks', 'Cool Drinks')], max_length=80)),
                ('dish_name', models.CharField(max_length=80, unique=True)),
                ('ingredients', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
